# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airbot/lm/rpc/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1b\x61irbot/lm/rpc/service.proto\x12\rLanguageModel\">\n\x0e\x45xtractRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"4\n\x0f\x45xtractResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tresponses\x18\x02 \x03(\t\"S\n\rDetectRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12#\n\x05image\x18\x03 \x01(\x0b\x32\x14.LanguageModel.Image\"4\n\x05Image\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"e\n\x0b\x42oundingBox\x12$\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x14.LanguageModel.Point\x12\x10\n\x08height_x\x18\x02 \x01(\x01\x12\x0f\n\x07width_y\x18\x03 \x01(\x01\x12\r\n\x05score\x18\x04 \x01(\x01\"K\n\x0e\x44\x65tectResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12)\n\x05\x62oxes\x18\x02 \x03(\x0b\x32\x1a.LanguageModel.BoundingBox\"j\n\x0eSegmentRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12$\n\x06prompt\x18\x02 \x01(\x0b\x32\x14.LanguageModel.Point\x12#\n\x05image\x18\x03 \x01(\x0b\x32\x14.LanguageModel.Image\"T\n\x0fSegmentResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\"\n\x04mask\x18\x02 \x01(\x0b\x32\x14.LanguageModel.Image\x12\r\n\x05score\x18\x03 \x01(\x01\x32^\n\x12InstructionService\x12H\n\x07\x65xtract\x12\x1d.LanguageModel.ExtractRequest\x1a\x1e.LanguageModel.ExtractResponse2\x9f\x01\n\x0cImageService\x12\x45\n\x06\x64\x65tect\x12\x1c.LanguageModel.DetectRequest\x1a\x1d.LanguageModel.DetectResponse\x12H\n\x07segment\x12\x1d.LanguageModel.SegmentRequest\x1a\x1e.LanguageModel.SegmentResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'airbot.lm.rpc.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_EXTRACTREQUEST']._serialized_start = 46
    _globals['_EXTRACTREQUEST']._serialized_end = 108
    _globals['_EXTRACTRESPONSE']._serialized_start = 110
    _globals['_EXTRACTRESPONSE']._serialized_end = 162
    _globals['_DETECTREQUEST']._serialized_start = 164
    _globals['_DETECTREQUEST']._serialized_end = 247
    _globals['_IMAGE']._serialized_start = 249
    _globals['_IMAGE']._serialized_end = 301
    _globals['_POINT']._serialized_start = 303
    _globals['_POINT']._serialized_end = 332
    _globals['_BOUNDINGBOX']._serialized_start = 334
    _globals['_BOUNDINGBOX']._serialized_end = 435
    _globals['_DETECTRESPONSE']._serialized_start = 437
    _globals['_DETECTRESPONSE']._serialized_end = 512
    _globals['_SEGMENTREQUEST']._serialized_start = 514
    _globals['_SEGMENTREQUEST']._serialized_end = 620
    _globals['_SEGMENTRESPONSE']._serialized_start = 622
    _globals['_SEGMENTRESPONSE']._serialized_end = 706
    _globals['_INSTRUCTIONSERVICE']._serialized_start = 708
    _globals['_INSTRUCTIONSERVICE']._serialized_end = 802
    _globals['_IMAGESERVICE']._serialized_start = 805
    _globals['_IMAGESERVICE']._serialized_end = 964
# @@protoc_insertion_point(module_scope)
